default:
  selector: textarea
  language: ko
  uploadimage_default_img_class: img-fluid
  paste_data_images: true
  toolbar: styleselect | bold italic | undo redo | table | forecolor | backcolor | emoticons
  plugins:
    - table
    - link
    - textcolor
    - colorpicker
    - wordcount
    - emoticons
    - uploadimage
    - paste
